# logging options
save_dir: ./results
project: kras_prediction
name: kras_evaluation

# task definition
data_config: data_config.yaml
task: binary
target: KRAS
num_classes: 1
cohorts: []
ext_cohorts: ["crc"]
clini_info: {}
seed: 42
label_dict:
  wildtype: 0
  mutated: 1

# model options
model: Transformer
model_config: {}
norm: raw
feats: ctranspath
input_dim: 768
num_tiles: -1
pad_tiles: false

# training options
folds: 5
num_epochs: 100
criterion: BCEWithLogitsLoss
optimizer: AdamW
lr_scheduler: CosineAnnealingLR
lr_scheduler_config:
  T_max: 100
lr: 0.00002
wd: 0.00002
bs: 1
stop_criterion: loss
val_check_interval: 500
num_samples: null